#!/bin/sh

# Use neovim, if present
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -v" \
  mkdir="mkdir -pv"

# Colors
alias \
  grep="grep --color=auto" \
  diff="diff --color=auto"

OS="$(uname)"
if [ "$OS" = "Darwin" ]
then
  alias ls="ls -G"
else
  alias ls="ls -hN --color=auto --group-directories-first"
fi


##################
# Custom aliases #
##################

# Shortcuts
alias cl="clear"
alias e='$EDITOR'
alias l="ls -al"
