prompt_order = [
	"username",
	"hostname",
	"directory",
	"git_branch",
	"git_commit",
	"git_state",
	"git_status",
	"cmd_duration",
	"line_break",
	"character"
]

[username]
disabled = true

[directory]
prefix = "| "
